# 配置文件版本号 请勿更改
ver: 5
# mirai的ip
ip: "127.0.0.1"
# mirai的端口号
port: 1111
# 服务器名字
ServerName: "Test Server"
UnconditionalAutoSync: true
AutoSyncPrefix: "#"
# 客户端聊天栏是否显示连接成功
NotifyPlayerChatsyncState: true
qqMsgStyle:
  0: "[玩家][%s%]:%msg%"
  1: "[§c管理员§r][%s%]:%msg%"
  2: "[§6腐竹§r][%s%]:%msg%"